version: '3.3'
name: 'hyx-docker-1'
services:
    nginx:
        container_name: nginx_env
        image: php:7.4.33-fpm
        ports: 
            - "80:80"
            - "81:81"
            - "82:82"
        volumes:
            - "./www:/var/www/html"
            - "./etc/nginx/conf.d:/etc/nginx/conf.d"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./etc/redis/redis.conf:/etc/redis/redis.conf"
        build: 
            context: .
            dockerfile: Dockerfile
    mysql:
        container_name: db
        image: "mysql:5.7.22"
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "laravel"
            MYSQL_ROOT_PASSWORD: "x"
            TZ: "Asia/Shanghai"  # 设置时区
        volumes:
            - "./mysql/my.cnf:/etc/mysql/my.cnf"
            - "./mysql/data_dir:/var/lib/mysql"
        command: mysqld --sql-mode=""
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
